[package]
name = "cloud"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
    "external_storage/protobuf-codec",
]
prost-codec = [
    "external_storage/prost-codec",
]

[dependencies]
error_code = { path = "../error_code", default-features = false }
external_storage = { path = "../external_storage", default-features = false }
failure = "0.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
openssl = "0.10"
protobuf = "2.8"
tokio = { version = "0.2.13", features = ["time"] }
tikv_util = { path = "../tikv_util", default-features = false }
rusoto_core = "0.45.0"