[package]
name = "gcp"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = ["kvproto/protobuf-codec"]
prost-codec = ["kvproto/prost-codec"]

[dependencies]
futures-util = { version = "0.3", default-features = false, features = ["io"] }
http = "0.2.0"
hyper = "0.13.3"
hyper-tls = "0.4.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tame-gcs = { version = "0.8.0", features = ["async-multipart"] }
tame-oauth = "0.4.2"
external_storage = { path = "../../external_storage" }
tokio = { version = "0.2.13", features = ["time"] }
url = "2.0"

[dev-dependencies]
matches = "0.1.8"
